// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klcckjmitczqbsueyjep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsY2Nram1pdGN6cWJzdWV5amVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDU4NjYsImV4cCI6MjA1NzM4MTg2Nn0._ddIM-Mo0rbLCRWV6Zj5KYdDD9t2cEuUw8sczOFqBAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);